/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu;

/**
 *
 * @author Heiler
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupotactico = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        userpanel = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cajauser = new javax.swing.JTextField();
        consultabtn = new javax.swing.JRadioButton();
        sesionbtn = new javax.swing.JRadioButton();
        contrapanel = new javax.swing.JPanel();
        contralabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cajacontra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpanel.setBackground(new java.awt.Color(255, 145, 76));

        userlabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        userlabel.setText("Usuario");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        cajauser.setBackground(new java.awt.Color(255, 145, 76));
        cajauser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajauser.setText("ingrese su numero de cedula");
        cajauser.setBorder(null);
        cajauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajauserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajauser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cajauser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 290, 110));

        consultabtn.setBackground(new java.awt.Color(255, 145, 76));
        grupotactico.add(consultabtn);
        consultabtn.setText("Consulta");
        consultabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultabtnActionPerformed(evt);
            }
        });
        jPanel1.add(consultabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 70, -1));

        sesionbtn.setBackground(new java.awt.Color(255, 145, 76));
        grupotactico.add(sesionbtn);
        sesionbtn.setText("Sesion");
        sesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sesionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 70, -1));

        contrapanel.setBackground(new java.awt.Color(255, 145, 76));

        contralabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        contralabel.setText("Contraseña");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        cajacontra.setBackground(new java.awt.Color(255, 145, 76));
        cajacontra.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajacontra.setText("ingrese su clave");
        cajacontra.setBorder(null);
        cajacontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajacontraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contrapanelLayout = new javax.swing.GroupLayout(contrapanel);
        contrapanel.setLayout(contrapanelLayout);
        contrapanelLayout.setHorizontalGroup(
            contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajacontra, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contralabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        contrapanelLayout.setVerticalGroup(
            contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contrapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contralabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cajacontra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(contrapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HeilerGa\\Documents\\NetBeansProjects\\kikehorario\\src\\main\\java\\resources\\forwad.png")); // NOI18N
        jButton1.setText("Next");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 70, -1));

        labelbg.setBackground(new java.awt.Color(255, 102, 51));
        labelbg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HeilerGa\\Documents\\NetBeansProjects\\kikehorario\\src\\main\\java\\resources\\background-sesion.jpeg")); // NOI18N
        labelbg.setText("jLabel1");
        jPanel1.add(labelbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajauserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajauserActionPerformed

    private void cajacontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajacontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajacontraActionPerformed

    private void consultabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultabtnActionPerformed
        // TODO add your handling code here:
        contrapanel.setVisible(false);
    }//GEN-LAST:event_consultabtnActionPerformed

    private void sesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionbtnActionPerformed
        // TODO add your handling code here:
        contrapanel.setVisible(!contrapanel.isVisible());
    }//GEN-LAST:event_sesionbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajacontra;
    private javax.swing.JTextField cajauser;
    private javax.swing.JRadioButton consultabtn;
    private javax.swing.JLabel contralabel;
    private javax.swing.JPanel contrapanel;
    private javax.swing.ButtonGroup grupotactico;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelbg;
    private javax.swing.JRadioButton sesionbtn;
    private javax.swing.JLabel userlabel;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
